name = "coverme"
compatibility_date = "2025-12-11"

[build]
command = "bun run build"
cwd = "./"
compatibility_date = "2025-12-11"

[build.upload]
format = "service-worker"

[env.production]
vars = { APP_ENV = "production" }

[env.development]
vars = { APP_ENV = "development" }