name = "coverme"
compatibility_date = "2025-12-11"
pages_build_output_dir = "build"

[build]
command = "bun run build"
cwd = "./"

[env.production]
vars = { APP_ENV = "production" }

[env.development]
vars = { APP_ENV = "development" }